//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp12
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_point
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> point_id { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual Product Product { get; set; }
    }
}
